### ISSUE TITLE
Can rajgoy01 use shorter paths?

### ISSUE THREAD

**Issue by hrw** [ARM-software/arm-systemready#69]
Many lines in log files have path to source file where message was located:

MediaIoProtocols:/home/rajgoy01/WORK/sbsa/sr_oob/SR/scripts/edk2-test/uefi-sct/SctPkg/TestCase/UEFI/EFI/Generic/SbbrRequiredUefiProtocols/BlackBoxTest/RequiredUefiProtocolsBBTestFunction.c:126:EFI_LOAD_FILE_PROTOCOL

Can those paths be shorter? Use some CI instead of rajgoy01 account?

**Comment by rajatgoyal47** [comment]
Hello Marcin,

Thank you for your suggestion. Please note that the path after "edk2-test" is not entirely under our control as it is determined by SctPkg.
We will be implementing changes that involve using the Common CI account for pre-built binaries. This will help reduce the length of the first half of the path leading to the source file (~3 Directory less).

Thanks,
Rajat

**Comment by hrw** [comment]
```/opt/uefi-sct/SctPkg/TestCase/UEFI/EFI/Generic/SbbrRequiredUefiProtocols/BlackBoxTest``` feels shorter

**Comment by edhay** [comment]
Hi Marcin, 

Achieving a path like for edk2-test
/opt/uefi-sct/SctPkg/TestCase/UEFI/EFI/Generic/SbbrRequiredUefiProtocols/BlackBoxTest
will bring in special handling in only some scripts in the ACS build system which we want to avoid.

Is the below path generated by CI acceptable?
/home/CIUSER/ACSv2.0.0/SR/scripts/edk2-test/uefi-sct/SctPkg/TestCase/UEFI/EFI/Generic/SbbrRequiredUefiProtocols/BlackBoxTest/RequiredUefiProtocolsBBTestFunction.c

This will be shorter than the example in the first message which is a non-standard path.

**Comment by hrw** [comment]
I am fine with whatever you make as it can always be removed from log.

**Comment by edhay** [comment]
Thank you for the reply, Marcin.

**Comment by chetan-rathore** [comment]
Hi @hrw,

With the recent CI infrastructure changes of using GitHub actions for building images, no internal paths or names are logged as part of ACS run. 

The new path is :  /home/runner/work/arm-systemready/arm-systemready/SR/scripts/edk2-test/uefi-sct/
SctPkg/TestCase/UEFI/EFI/Generic/EfiCompliant/BlackBoxTest/EfiCompliantBBTestReq
uired_uefi.c
 
Please note that due to the GitHub actions setup, arm-systemready will come twice.

Thanks,
ACS team
